name: 'Auto-version-action'
description: 'Auto version as an action inspired by shipkit-auto-version'
inputs:
  github-token:
    description: 'Token to access github'
    required: true
  version-spec:
    description: 'Version spec or key/value file for version spec'
    required: false
    default: 'version.properties'
  tag-prefix:
    description: 'Prefix used for version tags'
    require: false
    default: 'v'
outputs:
  latest-tagged-version:
    description: 'Version that the current version is based of'
  latest-tagged-version-name:
    description: 'Tag name'
  latest-tagged-version-sha:
    description: 'Commit hash associated with tag'
  version-spec:
    description: 'Version specification used'
  auto-version:
    description: 'Calculated version base of last_tagged_version'
runs:
  using: 'node20'
  main: 'dist/index.js'
